#!/usr/bin/env bash
# Walph-specific help and version display functions

# VERSION AND HELP
# ============================================================================

WALPH_VERSION="1.0.0"

show_version() {
    echo "Walph Riggum v${WALPH_VERSION}"
}

show_howto() {
    cat << 'EOF'
╔═══════════════════════════════════════════════════════════════════════════════╗
║                           WALPH RIGGUM                                        ║
║                    Autonomous Coding Loop for Claude                          ║
╚═══════════════════════════════════════════════════════════════════════════════╝

Walph runs Claude in an autonomous loop to plan and build software projects.
It uses Opus for planning and Sonnet for building, with fresh context each iteration.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 QUICK START
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  NEW PROJECT:
    walph init my-app --template api      # Create new project
    cd my-app
    # Edit specs/TEMPLATE.md with your requirements
    walph plan                            # Generate task list
    walph build                           # Build it!

  EXISTING PROJECT:
    cd your-project
    walph setup                           # Add Walph config (auto-detects stack)
    # Edit AGENTS.md with your build/test commands
    # Write specs in specs/
    walph plan                            # Generate task list
    walph build                           # Build it!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 COMMANDS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  walph init <name> [options]   Create a new project
    --template <type>           api, fullstack, cli, ios, android, capacitor, monorepo
    --stack <lang>              node, python, swift, kotlin
    --docker                    Include Docker configuration
    --postgres                  Include PostgreSQL setup

  walph setup [options]         Add Walph to existing project
    --stack <lang>              Override auto-detected stack
    --force                     Overwrite existing Walph files

  walph plan [options]          Generate implementation plan from specs
    --max-iterations N          Limit iterations (default: 50)
    --model <name>              Override model (default: opus)

  walph build [options]         Build from implementation plan
    --max-iterations N          Limit iterations (default: 50)
    --model <name>              Override model (default: sonnet)
    --monitor                   Enable tmux monitoring view

  walph status                  Show current progress
  walph reset                   Reset circuit breaker (if stuck)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 HOW IT WORKS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  1. WRITE SPECS          You describe what to build in specs/*.md
                          Be specific: endpoints, inputs, outputs, examples

  2. PLAN (Opus)          Claude analyzes specs and generates tasks
                          Creates IMPLEMENTATION_PLAN.md with checkboxes

  3. BUILD (Sonnet)       Claude implements ONE task per iteration:
                          - Picks first unchecked task
                          - Writes code, runs tests
                          - Marks task complete [x]
                          - Commits changes
                          - Repeats until done

  4. CIRCUIT BREAKER      Auto-stops if stuck:
                          - No file changes for 3 iterations
                          - Same error 5 times
                          - No commits for 5 iterations

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 PROJECT STRUCTURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  your-project/
  ├── .walph/                    # Walph configuration
  │   ├── config                 # Settings (iterations, models, thresholds)
  │   ├── PROMPT_plan.md         # Planning prompt (customizable)
  │   ├── PROMPT_build.md        # Building prompt (customizable)
  │   ├── logs/                  # Session logs
  │   └── state/                 # Circuit breaker state
  ├── specs/                     # Your requirements
  │   └── *.md                   # Feature specs (Walph reads all .md files)
  ├── AGENTS.md                  # Build/test/lint commands for Claude
  └── IMPLEMENTATION_PLAN.md     # Task list (generated by 'walph plan')

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 WRITING GOOD SPECS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  GOOD SPEC:                              BAD SPEC:
  ┌─────────────────────────────────┐     ┌─────────────────────────────────┐
  │ POST /users                     │     │ Handle user management          │
  │ Request: { "email": "..." }     │     │                                 │
  │ Response: { "id": 1, ... }      │     │                                 │
  │ Returns 400 if email invalid    │     │                                 │
  └─────────────────────────────────┘     └─────────────────────────────────┘

  Include:
  - Specific endpoints, function signatures, or CLI commands
  - Input/output examples
  - Error cases
  - Files to create/modify
  - Acceptance criteria as checkboxes

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 TIPS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  • Start small - first project should be simple
  • Review the plan - edit IMPLEMENTATION_PLAN.md before building if needed
  • Watch logs - tail -f .walph/logs/*.log
  • If stuck - walph reset, then check specs clarity
  • Commit often - Walph commits after each task (this is good!)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 MORE INFO
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  walph --help              Full command reference
  walph init --help         Project initialization options
  walph setup --help        Existing project setup options
  See: README.md, QUICKSTART.md

EOF
}

show_help() {
    cat << 'EOF'
Walph Riggum - Autonomous Coding Loop

USAGE:
    walph.sh <command> [options]

COMMANDS:
    init [name]       Initialize a new project (run 'walph init --help' for details)
    setup             Add Walph to existing project (run 'walph setup --help' for details)
    plan              Run in planning mode (generates IMPLEMENTATION_PLAN.md)
    build             Run in building mode (implements from plan) [default]
    status            Show current state and progress
    reset             Reset circuit breaker and state

OPTIONS:
    --max-iterations N    Maximum iterations (default: 50)
    --model MODEL         Override model for this run
    --monitor             Enable tmux monitoring view
    --dry-run             Show what would be run without executing
    -v, --verbose         Enable verbose output
    -h, --help            Show this help message
    --version             Show version

EXAMPLES:
    # New project
    walph.sh init my-app --stack node    # Initialize new project

    # Existing project
    cd my-existing-project
    walph.sh setup                       # Add Walph to existing project

    # Run Walph
    walph.sh plan                        # Generate implementation plan
    walph.sh build --max-iterations 10   # Build with limited iterations
    walph.sh status                      # Check current progress

WORKFLOW (new project):
    1. walph.sh init my-app       # Create project structure
    2. Edit specs/TEMPLATE.md     # Write your requirements
    3. walph.sh plan              # Generate task list
    4. walph.sh build             # Implement everything

WORKFLOW (existing project):
    1. cd my-existing-project
    2. walph.sh setup             # Add Walph config
    3. Edit AGENTS.md             # Add build/test commands
    4. Write specs in specs/      # Define what to build
    5. walph.sh plan              # Generate task list
    6. walph.sh build             # Implement everything

For more information, see README.md and QUICKSTART.md
EOF
}
